name: RSpec CI
on:
  push:
    branches:
      - 'main'
      - '*-maintenance'
      - '*-dev'
  pull_request:
    branches:
      - '*'
jobs:
  test:
    name: 'Ruby: ${{ matrix.ruby }}, Rails: ${{ matrix.env.RAILS_VERSION }}'
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
       include:
         # Rails 6.1 builds >= 2.5
         - ruby: truffleruby-head
           allow_failure: true
           env:
             RAILS_VERSION: '~> 6.1.0'
         - ruby: truffleruby-head
           env:
             RAILS_VERSION: '~> 6.1.0'
         - ruby: truffleruby-head
           env:
             RAILS_VERSION: '~> 6.1.0'
         - ruby: truffleruby-head
           env:
             RAILS_VERSION: '~> 6.1.0'
        
    env: ${{ matrix.env }}
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: script/clone_all_rspec_repos
      - run: bundle install --binstubs
      - run: script/run_build
        continue-on-error: ${{ matrix.allow_failure || false }}
